#!/bin/sh

set -o errexit
set -o nounset

python manage.py makemigrations
python manage.py migrate

python manage.py collectstatic --noinput
#python manage.py run_webhook

python manage.py runserver 0.0.0.0:8000